-- Seed Data for LitePOS

-- Insert Users (Password and PIN hash should be generated by bcrypt in real app, these are dummies)
-- Let's assume hash is just 'hashed_123456' for simplicity in this SQL dump
INSERT INTO users (username, password_hash, pin_hash, name, role) VALUES 
('owner', 'hashed_123456', 'hashed_123456', 'Owner Utama', 'owner'),
('kasir1', 'hashed_123456', 'hashed_123456', 'Kasir Satu', 'cashier');

-- Insert Categories
INSERT INTO categories (name, description) VALUES 
('Minuman', 'Berbagai macam minuman ringan dan air mineral'),
('Sembako', 'Kebutuhan pokok sehari-hari'),
('Snack', 'Makanan ringan dan camilan');

-- Insert Products
INSERT INTO products (category_id, sku_barcode, name, cost_price, selling_price, stock, minimum_stock) VALUES 
(1, '899999900001', 'Air Mineral 600ml', 2000, 3500, 100, 20),
(1, '899999900002', 'Teh Botol Manis', 3500, 5000, 50, 10),
(2, '899999900003', 'Beras Putih 5Kg', 55000, 62000, 20, 5),
(2, '899999900004', 'Minyak Goreng 1L', 14000, 16000, 30, 5),
(3, '899999900005', 'Keripik Kentang Original', 8000, 11000, 40, 10);

-- Insert System Settings
INSERT INTO system_settings (setting_key, setting_value) VALUES 
('allow_negative_stock', 'false'),
('qris_image_url', '');
